# Generated by Django 4.2.6 on 2023-10-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_votes_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters'),
        ),
        migrations.AddField(
            model_name='question',
            name='summary',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
